//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int codigo_empleado { get; set; }
        public string Nombre { get; set; }
        public decimal Horas_laboradas { get; set; }
        public decimal Salario_Hora { get; set; }
        public decimal Salario_Bruto { get; set; }
    }
}
